name: CI model to Dockerhub

#trigger
on: 
  pull_request:
    branches:
     - main

jobs:
  build_docker_image:
    runs-on: ubuntu-latest

    steps:
     - name: Check out the repo
       uses: actions/checkout@v2

     - name: Login to Docker Hub
       uses: docker/login-action@v2
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}

     - name: Build Docker image
       run: docker build -t abyc329/api_nyc_houseprice:v1 .

     - name: docker push to Dockerhub
       run: docker push abyc329/api_nyc_houseprice:v1

  
